### ISSUE TITLE
It makes the recycler view lag when it has many items

### ISSUE THREAD

**Issue by jahirfiquitiva** [plusCubed/recycler-fast-scroll#12]
Tested in a RecyclerView with GridLayoutManager, and about 600 items.

http://stackoverflow.com/questions/34365550/recyclerview-lags-on-scrolling

**Comment by pluscubed** [comment]
Just tested this again with 10000 text items - it does not inherently make the RecyclerView lag when scrolling with your finger. If it's lagging, that's a problem with how you're inflating/recycling views, not the library.

It does however lag when fast-scrolling through such a large list. Method profiling reveals it's because of how LayoutManager handles scrolling - the processing/delay comes from methods in there. I presume it's because it does not know whether each item is the same size, and basically has to bind/calculate all views up to that point. All fast scrolling libraries will have this problem.
